// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmglbdyrxnbucozwtscr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtZ2xiZHlyeG5idWNvend0c2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Mzk3MTAsImV4cCI6MjA2NDAxNTcxMH0.mvKcyTZzi6pytkNGYsuaToOvNgfd3JomjaVx_QNwPss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);